### PR TITLE
Fixing img display and large tidy-up

### PR DESCRIPTION
**Pull request by nicholascar**
* make BGS logo appear on all pages
* remove un-specialised templates - use system default instead
* added in nav.html for menu links - e.g. /search
* generalised apply.sh with environment variables

### CODE REVIEW

**Comment by KoalaGeo** [comment]
Looks good to me 
Will need to set below if use apply.sh but for docker deployment don't think we need to. 
VP_HOME
VP_THEME_HOME

**Comment by metazool** [comment]
Thank you so much @nicholascar - it looks good - we'll merge and test on our internal staging server but it's bound  to look better than our existing VocPrez customisation....

**Comment by nicholascar** [comment]
The main thing that this PR will do is to ensure that your instance uses the default templates, where possible. This ensures you get the updated SPARQL query page, search etc. So you only need to add templates for the bits you want to change and, in your case, it's only the `page.html` which applies the styling. No functional templates, e.g. `concept.html` need to be changed.

**Comment by metazool** [comment]
Ah we customised the original SPARQL query page very slightly because of the way  `_external=True` option to `url_for` renders the hostname when running in a container (ends up using and displaying the container hostname) 

I've put back just that one template in #3 for now with our tiny modification

**Pull request merged**
